theme: jekyll-theme-cayman
logo: https://bioboot.github.io/bimm143_F25/assets/img/logo.png
description: Bioinformatics and computational biology projects from BIMM 143
title: Gavin Ambrose – Bioinformatics & Data Science
