theme: jekyll-theme-minimal
logo: https://gambrose1.github.io/bimm143_github/Logo.png
description: Bioinformatics and computational biology projects from BIMM 143
title: Gavin Ambrose – Bioinformatics & Data Science
